# Generated by Django 5.1.3 on 2024-11-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_color_remove_car_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='currency',
        ),
    ]
